import type { Metadata, Viewport } from "next";
import HeaderSection from "./sections/header";
import BottomNavbar from "./sections/navbar";

export const metadata: Metadata = {
  title: "Dashboard - Zona Hotspot",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#f70a0a",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex min-h-screen w-full justify-center bg-secondary">
      <div
        className="
          flex min-h-screen w-full flex-col bg-background shadow-lg max-w-full"
      >
        <div className="sticky top-0 z-50">
          <HeaderSection />
        </div>
        <div
          className="
            flex flex-1 flex-col
            overflow-y-auto no-scrollbar
            pb-24
          "
        >
          {children}
        </div>
        <div className="sticky bottom-0 z-50 h-20">
          <BottomNavbar />
        </div>
      </div>
    </main>
  );
}
