import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: "Authentication - Zona Hotspot",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex min-h-dvh w-full justify-center bg-secondary">
      {children}
    </main>
  );
}
