import type { Metadata, Viewport } from "next";
import ClientProviders from "@/components/providers/client-provider";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Home - Zona Hotspot",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#f70a0a",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/icons/chain.svg" type="image/x-icon" />
      </head>
      <body className="flex min-h-screen overflow-x-hidden font-tommy-regular">
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
