import type { Metadata, Viewport } from "next";
import LenisProvider from "@/components/providers/lenis-provider";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "PWA App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex font-nexa min-h-screen overflow-x-hidden">
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
