import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: "Invoice - Zona Hotspot",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#f70a0a",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function InvoiceLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex flex-1">
      {children}
    </main>
  );
}
